openapi: 3.0.2
info:
  title: Quantum Services
  description: This API enables the generation of quantum services.
  version: '1.0'
  termsOfService: 'https://quantum.spilab.es/terms'
  contact:
    name: Spilab
    url: 'https://spilab.es'
    email: info@spilab.es
tags:
  - name: quantum
    description: Everything about your Quantum Service
  - name: quantum_code
    description: Everything about your quantum service code and circuits
paths:
  /circuit/BernsteinVaziraniIBMquirk:
    get:
      tags:
        - quantum_code
      summary: Get the circuit implementation of Bernstein-Vazirani Algorithm
      description: ''
      operationId: BernsteinVaziraniIBMquirk
      parameters:
        - name: machine
          in: query
          description: Algorithm that tries to learn a string encoded in a function
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: string
        - name: shots
          in: query
          description: Number of shots
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid execution
      x-quantumCode: 'https://algassert.com/quirk#circuit={"cols":[["H","H","H"],[1,1,1,"X"],[1,1,1,"H"],["•",1,1,"X"],[1,"•",1,"X"],[1,1,"•","X"],["H","H","H"],["Measure","Measure","Measure"]]}'
      x-quantumProvider: 'ibm'

  /circuit/BernsteinVaziraniIBMqiskit:
    get:
      tags:
        - quantum_code
      summary: Get the circuit implementation of Bernstein-Vazirani Algorithm
      description: ''
      operationId: BernsteinVaziraniIBMqiskit
      parameters:
        - name: machine
          in: query
          description: Algorithm that tries to learn a string encoded in a function
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: string
        - name: shots
          in: query
          description: Number of shots
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid execution
      x-quantumCode: 'https://bitbucket.org/spilab/quantum-circuits-code/raw/3f6f114350c81ed728955e68a84fb34d1154fa17/Bernstein-Vazirani.py'
      x-quantumProvider: 'ibm'
      
  /circuit/DeutschJozsaIBMquirk:
    get:
      tags:
        - quantum_code
      summary: Get the circuit implementation of Deutsch Jozsa Algorithm
      description: ''
      operationId: DeutschJozsaIBMquirk
      parameters:
        - name: machine
          in: query
          description: Algorithm that determines if a function is balanced or constant
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: string
        - name: shots
          in: query
          description: Number of shots
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid execution
      x-quantumCode: 'https://algassert.com/quirk#circuit={"cols":[["H","H","H"],["X",1,"X","X"],[1,1,1,"H"],["•",1,1,"X"],[1,"•",1,"X"],[1,1,"•","X"],["X",1,"X"],["H","H","H"],["Measure","Measure","Measure"]]}'
      x-quantumProvider: 'ibm'
  /circuit/DeutschJozsaIBMqiskit:
    get:
      tags:
        - quantum_code
      summary: Get the circuit implementation of Deutsch Jozsa Algorithm
      description: ''
      operationId: DeutschJozsaIBMqiskit
      parameters:
        - name: machine
          in: query
          description: Algorithm that determines if a function is balanced or constant
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: string
        - name: shots
          in: query
          description: Number of shots
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid execution
      x-quantumCode: 'https://bitbucket.org/spilab/quantum-circuits-code/raw/3beac7c00f41e743859570856298b928eeda54d3/Deutsch%E2%80%93Jozsa_algorithm.py'
      x-quantumProvider: 'ibm'
      
  /findByCategory:
    get:
      tags:
        - quantum
      summary: Finds quantum service by category
      description: Multiple status values can be provided with comma separated strings
      operationId: findServiceByCategory
      parameters:
        - name: qua
          in: query
          description: Status values that need to be considered for filter
          required: true
          style: form
          explode: false
          deprecated: true
          schema:
            type: array
            items:
              type: string
              enum:
                - annealing
                - gate-based
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quantum'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quantum'
        '400':
          description: Invalid status value
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
components:
  schemas:
    Category:
      title: quantum category
      description: A category for a quantum code
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          pattern: ^[a-zA-Z0-9]+[a-zA-Z0-9\.\-_]*[a-zA-Z0-9]+$
      xml:
        name: Category
    quantum:
      title: quantum code
      description: quantum code 
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: gate-based
      xml:
        name: quantum