# This is a basic workflow to help you get started with Actions

name: Automate deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Sonar files
        env:
           EMAIL: ${{ secrets.EMAIL }}
           NAME: ${{ secrets.NAME }}
        run: |
         git init
         git config user.email "$EMAIL"
         git config user.name "$NAME"
         git config --list   
         git clone https://github.com/javierrome236/sonarQuantum.git
         python sonar.py
         cd ./sonarQuantum
         echo "$EMAIL"
         git add *
         git commit -m "Commit"
         git push origin master
      - name: Check python project
        run: |
         cd ./openapi_server
         python -m compileall .
         #python -m openapi_server          
      - name: Deploy Stage
        run: curl -X POST -F 'name=python' -F 'yaml=https://raw.githubusercontent.com/javierrome236/quantumDeployment/main/openapi.yaml' http://quantumservicesdeployment.spilab.es:8081/docker

          


