# This is a basic workflow to help you get started with Actions

name: Automate deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [14]
        python: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: java -jar openapi-generator-cli.jar generate -i openapi.yaml -g python-quantum -o .
    
    
    
    
    
    #- name: Get OpenAPI files Action
     # id: getfiles
      #uses: mbowman100/swagger-validator-action@master
      #with:
       # files: |
       #   ./openapi.yaml

